### ISSUE TITLE
client.application_uri = "urn:example.org:FreeOpcUa:python-opcua"

### ISSUE THREAD

**Issue by ganesh1306** [AndreasHeine/SecurePythonOpcUaClient#1]
client.application_uri = "urn:example.org:FreeOpcUa:python-opcua"
did you changed this application uri in client.py file because it is self.application_uri = "urn:freeopcua:client"
can we change this URI 

how you are generating private-key-example.pem  ,certificate-example.der 
for connecting to server is these files are necessary do in server side to this certs has to be trusted

**Comment by AndreasHeine** [comment]
`client.application_uri = "urn:example.org:FreeOpcUa:python-opcua"`

the uri of your application has to match the uri provided in the certificats subjectAltname extention
you can change it to whatever u like but then you have to generate new certs with matching uri!!!
you should prefer this example https://github.com/AndreasHeine/SecurePythonOpcUaClient/tree/master/x509v3

> how you are generating private-key-example.pem ,certificate-example.der

you can use openssl for generating them: https://github.com/AndreasHeine/SecurePythonOpcUaServer

> for connecting to server is these files are necessary do in server side to this certs has to be trusted

it depends on the server (used opcua sdk/stack)! some do need the client cert as trusted some dont python opcua to python opc ua dont need it. simple explaination if you or anyone else can make its own passport (x509 cert) why should i have a copy of it!? ;)

**Comment by ganesh1306** [comment]
my point is that how to make server to trust in real-time machines what the we have generated 
in prosys server, we have to trust the certs in the certificate section

**Comment by AndreasHeine** [comment]
or just copy the client cert into the prosys certs folder!

**Comment by ganesh1306** [comment]
what about real time plc servers which as opc ua servers

**Comment by AndreasHeine** [comment]
i tested python opc ua against s7-1500 plcs with opc ua servers and aslo the s7-1500 opcua client functionblocks and it works fine!

PLC: S7-1513F (v2.6 - 6ES7 513-1FL02-0AB0 V02.06.01)
